version: '3.8'
services:
#  server:
#    build: server/
#    ports:
#      - '5000:5000'
#    depends_on:
#      - postgres
#    environment:
#      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase
#  client:
#    build: client/
#    ports:
#      - '3000:3000'
#    depends_on:
#      - server

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: